import type { Metadata } from "next";
import "./globals.css";
import { inter } from '../config/font';



export const metadata: Metadata = {
  title: {
    template: "%s - Teslo | Shop 14 - FR",
    default: "Home - Teslo | Shop 14 - FR"
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
